const EventTypes = {
  QR_SCANNED: 1,
  AUDIO_STARTED: 2,
  AUDIO_PAUSED: 3,
  AUDIO_STOPPED: 4,
  AUDIO_SEEKED: 5,
  AUDIO_COMPLETED: 6,
  AUDIO_VOLUME_CHANGED: 7,
  AUDIO_MUTED: 8,
  AUDIO_UNMUTED: 9,
  EXHIBIT_FAVOURITED: 10,
  EXHIBIT_UNFAVOURITED: 11,
};

module.exports = EventTypes;
